services:
  eureka:
    build: eureka-server
    mem_limit: 350m
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:8761/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 60

  auth-server:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: auth-server
    mem_limit: 512m
    healthcheck:
      test: [ "CMD", "curl", "-fs", "http://localhost:9999/actuator/health" ]
      interval: 5s
      timeout: 2s
      retries: 60
    depends_on:
      eureka:
        condition: service_healthy

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SERVER_SSL_KEY_STORE=file:/keystore/edge.p12
      - SERVER_SSL_KEY_STORE_PASSWORD=greatseo
    volumes:
      - ./keystore:/keystore
    build: api-gateway
    mem_limit: 350m
    ports:
      - "8443:8443"
    depends_on:
      auth-server:
        condition: service_healthy

networks:
  default:
    name: greatseo
    external: true
