services:
  eureka:
    build: eureka-server
    mem_limit: 350m

  gateway:
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    build: api-gateway
    mem_limit: 350m
    ports:
      - "8080:8080"

networks:
  default:
    name: greatseo
    external: true