spring:
  application:
    name: recommendation-service
  profiles:
    active:
      - local

logging:
  level:
    root: INFO
    dev.greatseo.backend: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 3003
      database: greatseo
      username: greatseo
      password: greatseo

server:
  port: 7002

---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: 172.26.0.3
      port: 27017
      database: greatseo
      username: greatseo
      password: greatseo

server:
  port: 8080