server:
  port: 7002

spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 3003
      database: greatseo
      username: greatseo
      password: greatseo