spring:
  application:
    name: product-service
  profiles:
    active:
      - local

logging:
  level:
    root: INFO
    dev.greatseo.backend: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 3003
      database: greatseo
      username: greatseo
      password: greatseo

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup


spring.cloud.stream.bindings.input.consumer:
  maxAttempts: 3
  backOffInitialInterval: 500
  backOffMaxInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.bindings.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.bindings.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

#default value
management:
  endpoints:
    web:
      exposure.include: "*"
      base-path: /actuator
      path-mapping:
        health: health
    health.show-details: "ALWAYS"

server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings.input:
      destination: products
      group: productsGroup

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: greatseo
    password: greatseo

  cloud.stream.kafka.binder.brokers: kafka

  #cloud.stream.kafka.binder.brokers: kafka

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: r2dbc-mongo
      port: 27017
      database: greatseo
      username: greatseo
      password: greatseo

server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/