server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker

  cloud.stream:
    defaultBinder: rabbit
    bindings:
      product-in-0:
        destination: product
        group: productGroup
        consumer:
          retry-template-name: defaultRetryTemplate #<retry-template-bean 명 등록>
    kafka.binder:
      brokers: kafka
      defaultBrokerPort: 9092

  rabbitmq:
    host: rabbit-haproxy
    port: 5672
    username: greatseo
    password: greatseo

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: r2dbc-mongo
      port: 27017
      database: greatseo
      username: greatseo
      password: greatseo

management:
  endpoints:
    web:
      exposure.include: "*"
      base-path: /actuator
      path-mapping:
        health: health
    health.show-details: "ALWAYS"

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/