spring:
  application:
    name: product-service
  profiles:
    active:
      - local

logging:
  level:
    root: INFO
    dev.greatseo.backend: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 3003
      database: greatseo
      username: greatseo
      password: greatseo

spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    products-in-0:
      destination: products
      group: productGroup

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

#default value
management:
  endpoints:
    web:
      exposure.include: "*"
      base-path: /actuator
      path-mapping:
        health: health
    health.show-details: "ALWAYS"

server:
  port: 7001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker

  rabbitmq.host: rabbitmq

  #cloud.stream.kafka.binder.brokers: kafka

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: r2dbc-mongo
      port: 27017
      database: greatseo
      username: greatseo
      password: greatseo

server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/