spring:
  application:
    name: product-service
  profiles:
    active:
      - local

logging:
  level:
    root: INFO
    dev.greatseo.backend: DEBUG

---
spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: localhost
      port: 3003
      database: greatseo
      username: greatseo
      password: greatseo

spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    products-out-0:
      destination: products
      content-type: application/json
    products-in-0:
      destination: products
      group: productGroup

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

server:
  port: 7001

---
spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      host: r2dbc-mongo
      port: 27017
      database: greatseo
      username: greatseo
      password: greatseo

server:
  port: 8080