spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  eureka-username: u
  eureka-password: p
  eureka-server: eureka

spring.data:
  mongodb:
    #auto-index-creation: true
    #authentication-database: admin
    host: r2dbc-mongo
    port: 27017
    database: product-db
    #username: greatseo
    #password: greatseo

spring.rabbitmq:
  host: rabbit-haproxy
  port: 5672
  username: greatseo
  password: greatseo

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092