spring:
  config:
    activate:
      on-profile: local
server:
  port: 7000

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

spring.cloud.stream:
  defaultBinder: rabbit
  function:
    definition: receiverMessageHandler
  bindings:
    products-out-0:
      destination: products
      content-type: application/json
    products-in-0:
      destination: products


spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  product-service:
    host: product
    port: 8080
  recommendation-service:
    host: recommendation
    port: 8080
  review-service:
    host: review
    port: 8080