#application.yml
spring:
  application:
    name: product-composite
  profiles:
    active:
      - local
    group:
      local:
        - service-local
        - database-local
      docker:
        - service-docker
        - database-docker
    include:
      - service
      - database
