spring:
  config:
    activate:
      on-profile: local
server:
  port: 7000

spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    product-out-0:
      destination: product
      content-type: application/json
    recommendation-out-0:
      destination: recommendation
      content-type: application/json
    review-out-0:
      destination: review
      content-type: application/json

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

management:
  health:
    externalApiHealthStatus:
      enabled: true
    ping:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings:
      product-out-0:
        destination: product
        content-type: application/json
      recommendation-out-0:
        destination: recommendation
        content-type: application/json
      review-out-0:
        destination: review
        content-type: application/json

  rabbitmq:
    host: rabbit-haproxy
    port: 5672
    username: greatseo
    password: greatseo
  cloud.stream.kafka.binder.brokers: kafka

management:
  health:
    externalApiHealthStatus:
      enabled: true
    ping:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/