spring:
  config:
    activate:
      on-profile: local

server:
  port: 7000

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

---
spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  eureka-username: u
  eureka-password: p
  eureka-server: eureka

spring.rabbitmq:
  host: rabbit-haproxy
  port: 5672
  username: greatseo
  password: greatseo

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092