spring:
  config:
    activate:
      on-profile: local
server:
  port: 7000

app:
  product-service:
    host: localhost
    port: 7001
  recommendation-service:
    host: localhost
    port: 7002
  review-service:
    host: localhost
    port: 7003

spring.cloud.stream:
  defaultBinder: rabbit
  bindings:
    products-out-0:
      destination: products
      content-type: application/json

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: greatseo
  password: greatseo

management:
  health:
    externalApiHealthStatus:
      enabled: true
    ping:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

---
spring:
  config:
    activate:
      on-profile: docker

  cloud.stream:
    defaultBinder: rabbit
    default.contentType: application/json
    bindings:
      products-out-0:
        destination: products
        content-type: application/json

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: greatseo
    password: greatseo
  cloud.stream.kafka.binder.brokers: kafka

server:
  port: 8080

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/