spring:
  config:
    activate:
      on-profile: docker

server:
  port: 8080

app:
  eureka-username: u
  eureka-password: p
  eureka-server: eureka

spring.rabbitmq:
  host: rabbit-haproxy
  port: 5672
  username: greatseo
  password: greatseo

spring.datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://r2dbc-maria:3306/greatseo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  username: greatseo
  password: greatseo

spring.jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql

spring.cloud.stream.kafka.binder:
  brokers: kafka
  defaultBrokerPort: 9092