server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker

  cloud.stream:
    defaultBinder: rabbit
    bindings:
      reviews-in-0:
        destination: reviews
        group: reviewGroup
        consumer:
          retry-template-name: defaultRetryTemplate #<retry-template-bean 명 등록>
        #error-handler-definition: productErrorHandler
    kafka.binder:
      brokers: 127.0.0.1
      defaultBrokerPort: 9092

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://r2dbc-maria:3306/greatseo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: greatseo
    password: greatseo

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka/