spring:
  config:
    activate:
      on-profile: local

server:
  port: 7003

app:
  eureka-username: u
  eureka-password: p
  eureka-server: localhost

spring.datasource:
  driver-class-name: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3002/greatseo?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
  username: greatseo
  password: greatseo

spring.jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true #To beautify or pretty print the SQL
      show_sql: true #show sql

spring.rabbitmq:
  host: localhost
  port: 5672
  username: greatseo
  password: greatseo

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092